version: "3.9"

services:

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"
    networks:
      - app-network
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8086:8086"
    depends_on:
      - inventory-service
    networks:
      - app-network


networks:
  app-network: